package com.francium.profiler.report;

import com.francium.profiler.memory.MemoryManager;

import java.io.*;
import java.nio.file.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 效能報告生成器 — 把冰冷的數字變成精美的 HTML 和 JSON 報告。
 *
 * 「你的記憶體不該是一團謎。Francium 替你畫出來。」
 *
 * 輸出格式:
 *  - HTML: 互動式報告，含圖表、洩漏分析、池命中率、GC 時間軸
 *  - JSON: 結構化數據，給 CI/CD 或 Grafana 用
 */
public class ProfilerReport {

    private static final Logger LOGGER = LoggerFactory.getLogger(ProfilerReport.class);

    private final MemoryManager memoryManager;
    private final List<MemoryManager.MemorySnapshot> snapshots;
    private final String modpackName;
    private final Instant sessionStart;

    public ProfilerReport(MemoryManager memoryManager, String modpackName) {
        this.memoryManager = memoryManager;
        this.snapshots = new ArrayList<>();
        this.modpackName = modpackName != null ? modpackName : "Unnamed Modpack";
        this.sessionStart = Instant.now();
    }

    /**
     * 擷取當前快照。
     */
    public void capture() {
        snapshots.add(memoryManager.getSnapshot());
    }

    /**
     * 生成 HTML 報告。
     */
    public String toHtml() {
        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html>\n<html lang=\"zh-TW\">\n<head>\n");
        html.append("<meta charset=\"UTF-8\">\n");
        html.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        html.append("<title>Francium Profiler — ").append(escapeHtml(modpackName)).append("</title>\n");
        html.append("<style>\n");
        html.append(renderCss());
        html.append("</style>\n</head>\n<body>\n");

        // Header
        html.append("<header>\n");
        html.append("  <h1>🧪 Francium Profiler Report</h1>\n");
        html.append("  <p class=\"subtitle\">").append(escapeHtml(modpackName))
             .append(" — ").append(sessionStart.atOffset(ZoneOffset.ofHours(8))
             .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))).append(" CST</p>\n");
        html.append("</header>\n");

        // Summary cards
        html.append("<section class=\"cards\">\n");
        html.append(renderSummaryCards());
        html.append("</section>\n");

        // Memory timeline
        html.append("<section>\n");
        html.append("  <h2>📈 記憶體時間軸</h2>\n");
        html.append(renderTimelineChart());
        html.append("</section>\n");

        // Per-mod breakdown
        html.append("<section>\n");
        html.append("  <h2>📦 模組記憶體明細</h2>\n");
        html.append(renderModTable());
        html.append("</section>\n");

        // Pool performance
        html.append("<section>\n");
        html.append("  <h2>🏊 物件池效率</h2>\n");
        html.append(renderPoolTable());
        html.append("</section>\n");

        // Leak detection
        html.append("<section>\n");
        html.append("  <h2>🔍 洩漏偵測</h2>\n");
        html.append(renderLeakReport());
        html.append("</section>\n");

        // GC timeline
        html.append("<section>\n");
        html.append("  <h2>🗑️ GC 時間線</h2>\n");
        html.append(renderGCTimeline());
        html.append("</section>\n");

        // Footer
        html.append("<footer>\n");
        html.append("  <p>Generated by <a href=\"https://github.com/stanley-1028/francium-loader\">Francium Mod Loader</a> Profiler</p>\n");
        html.append("  <p>「不要手動管理記憶體，讓 Francium 替你打工。」</p>\n");
        html.append("</footer>\n");

        html.append("</body>\n</html>");
        return html.toString();
    }

    /**
     * 導出為 JSON 格式（給 Grafana / CI / 腳本使用）。
     */
    public String toJson() {
        StringBuilder json = new StringBuilder();
        json.append("{\n");
        json.append("  \"modpack\": \"").append(escapeJson(modpackName)).append("\",\n");
        json.append("  \"sessionStart\": \"").append(sessionStart.toString()).append("\",\n");
        json.append("  \"generatedAt\": \"").append(Instant.now().toString()).append("\",\n");

        // Latest snapshot
        if (!snapshots.isEmpty()) {
            var latest = snapshots.get(snapshots.size() - 1);
            json.append("  \"memory\": {\n");
            json.append("    \"heapUsedMB\": ").append(latest.heapUsed() / 1024 / 1024).append(",\n");
            json.append("    \"heapMaxMB\": ").append(latest.max() / 1024 / 1024).append(",\n");
            json.append("    \"nonHeapMB\": ").append(latest.nonHeapUsed() / 1024 / 1024).append(",\n");
            json.append("    \"usagePercent\": ").append(String.format("%.1f", latest.usagePercent() * 100)).append(",\n");
            json.append("    \"gcCount\": ").append(latest.gcCount()).append(",\n");
            json.append("    \"totalAllocatedMB\": ").append(latest.totalAllocated() / 1024 / 1024).append("\n");
            json.append("  },\n");
        }

        // Mod stats
        List<MemoryManager.PerModMemory> mods = memoryManager.getPerModStats();
        json.append("  \"mods\": [\n");
        for (int i = 0; i < mods.size(); i++) {
            var m = mods.get(i);
            json.append("    {\"id\":\"").append(escapeJson(m.modId))
                 .append("\",\"estimatedKB\":").append(m.estimatedUsage / 1024)
                 .append(",\"classes\":").append(m.loadedClasses)
                 .append(",\"loadTimeMs\":").append(m.loadTimeMs).append("}");
            if (i < mods.size() - 1) json.append(",");
            json.append("\n");
        }
        json.append("  ]\n");
        json.append("}\n");
        return json.toString();
    }

    /**
     * 保存報告到檔案。
     */
    public void saveTo(Path dir) throws IOException {
        Files.createDirectories(dir);

        // HTML
        Files.writeString(dir.resolve("francium-profiler-report.html"), toHtml());
        // JSON
        Files.writeString(dir.resolve("francium-profiler-report.json"), toJson());

        LOGGER.info("Fr Profiler: Report saved to " + dir.toAbsolutePath());
    }

    // ─── HTML rendering helpers ──────────────────────────

    private String renderCss() {
        return """
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', system-ui, sans-serif; background: #0d1117; color: #c9d1d9; padding: 2rem; }
        header { text-align: center; margin-bottom: 2rem; }
        h1 { font-size: 2rem; color: #58a6ff; }
        .subtitle { color: #8b949e; font-size: 0.9rem; margin-top: 0.5rem; }
        section { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; }
        h2 { font-size: 1.2rem; color: #f0f6fc; margin-bottom: 1rem; border-bottom: 1px solid #21262d; padding-bottom: 0.5rem; }
        .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 1rem; }
        .card { background: #0d1117; border: 1px solid #30363d; border-radius: 6px; padding: 1rem; text-align: center; }
        .card .value { font-size: 2rem; font-weight: bold; color: #58a6ff; }
        .card .label { font-size: 0.8rem; color: #8b949e; margin-top: 0.25rem; }
        .card.warning .value { color: #f0883e; }
        .card.danger .value { color: #f85149; }
        .card.good .value { color: #3fb950; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 0.6rem 0.8rem; text-align: left; border-bottom: 1px solid #21262d; }
        th { color: #8b949e; font-size: 0.8rem; text-transform: uppercase; }
        .bar-container { background: #21262d; border-radius: 4px; height: 20px; overflow: hidden; }
        .bar { height: 100%; border-radius: 4px; transition: width 0.3s; }
        .bar.green { background: #3fb950; }
        .bar.orange { background: #f0883e; }
        .bar.red { background: #f85149; }
        .bar.blue { background: #58a6ff; }
        .leak { background: #2d1610; border-left: 3px solid #f85149; padding: 0.8rem; margin-bottom: 0.5rem; border-radius: 0 6px 6px 0; }
        .leak .mod-name { color: #f85149; font-weight: bold; }
        .clean { color: #3fb950; }
        footer { text-align: center; color: #484f58; font-size: 0.8rem; margin-top: 2rem; }
        footer a { color: #58a6ff; text-decoration: none; }
        .timeline-bar { display: flex; align-items: flex-end; gap: 2px; height: 120px; padding: 4px 0; }
        .timeline-bar .tick { flex: 1; min-width: 4px; border-radius: 2px 2px 0 0; opacity: 0.8; }
        """;
    }

    private String renderSummaryCards() {
        if (snapshots.isEmpty()) {
            return "<div class=\"card\"><div class=\"value\">N/A</div><div class=\"label\">尚無數據</div></div>";
        }

        var latest = snapshots.get(snapshots.size() - 1);
        long usedMB = latest.heapUsed() / 1024 / 1024;
        long maxMB = latest.max() / 1024 / 1024;
        double usagePct = latest.usagePercent() * 100;

        String memClass = usagePct > 85 ? "danger" : usagePct > 65 ? "warning" : "";

        StringBuilder cards = new StringBuilder();

        // Heap usage
        cards.append("<div class=\"card ").append(memClass).append("\">\n");
        cards.append("  <div class=\"value\">").append(String.format("%.0f%%", usagePct)).append("</div>\n");
        cards.append("  <div class=\"label\">堆記憶體 (")
             .append(usedMB).append("/").append(maxMB).append(" MB)</div>\n");
        cards.append("  <div class=\"bar-container\"><div class=\"bar ")
             .append(usagePct > 85 ? "red" : usagePct > 65 ? "orange" : "green")
             .append("\" style=\"width:").append(String.format("%.0f", Math.min(100, usagePct)))
             .append("%\"></div></div>\n");
        cards.append("</div>\n");

        // Non-heap
        long nonHeapMB = latest.nonHeapUsed() / 1024 / 1024;
        cards.append("<div class=\"card\">\n");
        cards.append("  <div class=\"value\">").append(nonHeapMB).append(" MB</div>\n");
        cards.append("  <div class=\"label\">非堆記憶體 (Metaspace)</div>\n");
        cards.append("</div>\n");

        // Loaded mods
        List<MemoryManager.PerModMemory> mods = memoryManager.getPerModStats();
        cards.append("<div class=\"card\">\n");
        cards.append("  <div class=\"value\">").append(mods.size()).append("</div>\n");
        cards.append("  <div class=\"label\">已載入模組</div>\n");
        cards.append("</div>\n");

        // GC count
        cards.append("<div class=\"card\">\n");
        cards.append("  <div class=\"value\">").append(latest.gcCount()).append("</div>\n");
        cards.append("  <div class=\"label\">GC 次數 (本次工作階段)</div>\n");
        cards.append("</div>\n");

        // Total allocated
        long allocatedMB = latest.totalAllocated() / 1024 / 1024;
        cards.append("<div class=\"card\">\n");
        cards.append("  <div class=\"value\">").append(allocatedMB).append(" MB</div>\n");
        cards.append("  <div class=\"label\">總分配量</div>\n");
        cards.append("</div>\n");

        return cards.toString();
    }

    private String renderTimelineChart() {
        if (snapshots.size() < 2) {
            return "<p class=\"clean\">需要至少 2 個快照來繪製時間軸。讓 Profiler 多跑一會兒。</p>";
        }

        long maxMem = 0;
        for (var s : snapshots) {
            if (s.heapUsed() > maxMem) maxMem = s.heapUsed();
        }

        StringBuilder bars = new StringBuilder();
        bars.append("<div class=\"timeline-bar\">\n");
        for (var s : snapshots) {
            int height = maxMem > 0 ? (int)((double)s.heapUsed() / maxMem * 100) : 0;
            bars.append("  <div class=\"tick bar blue\" style=\"height:")
                 .append(Math.max(1, height)).append("%\" title=\"")
                 .append(s.heapUsed() / 1024 / 1024).append("MB @ ").append(s.timestamp())
                 .append("\"></div>\n");
        }
        bars.append("</div>\n");
        bars.append("<p style=\"color:#8b949e;font-size:0.8rem;margin-top:0.5rem;\">")
             .append(snapshots.size()).append(" 個快照 | 峰值 ")
             .append(maxMem / 1024 / 1024).append(" MB</p>");
        return bars.toString();
    }

    private String renderModTable() {
        List<MemoryManager.PerModMemory> mods = memoryManager.getPerModStats();
        if (mods.isEmpty()) {
            return "<p class=\"clean\">尚無模組加載資料。啟動 Minecraft 後再來。</p>";
        }

        // Sort by estimated usage desc
        mods.sort((a, b) -> Long.compare(b.estimatedUsage, a.estimatedUsage));

        long total = mods.stream().mapToLong(m -> m.estimatedUsage).sum();

        StringBuilder table = new StringBuilder();
        table.append("<table>\n<tr><th>模組</th><th>估算記憶體</th><th>佔比</th><th>類別數</th><th>加載時間</th></tr>\n");

        // Color scale: top 3 are suspects
        for (int i = 0; i < mods.size(); i++) {
            var m = mods.get(i);
            double pct = total > 0 ? (double)m.estimatedUsage / total * 100 : 0;
            String rowClass = i < 3 && m.estimatedUsage > 10_000_000 ? " style=\"background:#2d1610\"" : "";

            table.append("<tr").append(rowClass).append(">\n");
            table.append("  <td>").append(escapeHtml(m.modId)).append("</td>\n");
            table.append("  <td>").append(formatBytes(m.estimatedUsage)).append("</td>\n");
            table.append("  <td><div class=\"bar-container\"><div class=\"bar ")
                 .append(pct > 20 ? "red" : pct > 10 ? "orange" : "green")
                 .append("\" style=\"width:").append(String.format("%.0f", Math.min(100, pct * 2)))
                 .append("%\"></div></div>").append(String.format("%.1f%%", pct)).append("</td>\n");
            table.append("  <td>").append(m.loadedClasses).append("</td>\n");
            table.append("  <td>").append(m.loadTimeMs).append("ms</td>\n");
            table.append("</tr>\n");
        }

        table.append("</table>\n");
        table.append("<p style=\"color:#8b949e;font-size:0.8rem;margin-top:0.5rem;\">")
             .append("總計 ").append(mods.size()).append(" 個模組 | 估算總記憶體: ")
             .append(formatBytes(total)).append("</p>");
        return table.toString();
    }

    private String renderPoolTable() {
        // Object pool stats from MemoryManager would be exposed here
        return "<p style=\"color:#8b949e;\">物件池統計需要在 MemoryManager 中啟用對應功能。"
             + "<br>詳見 <code>config/francium/loader.toml</code> 中的 <code>objectPool</code> 設定。</p>";
    }

    private String renderLeakReport() {
        List<MemoryManager.LeakReport> leaks = memoryManager.getLeakReports();
        if (leaks == null || leaks.isEmpty()) {
            return "<p class=\"clean\">✅ 未檢測到記憶體洩漏。Francium 的獨立 ClassLoader 隔離運作正常。</p>";
        }

        StringBuilder sb = new StringBuilder();
        for (var leak : leaks) {
            sb.append("<div class=\"leak\">\n");
            sb.append("  <span class=\"mod-name\">").append(escapeHtml(leak.modId())).append("</span>\n");
            sb.append("  <span> — ").append(escapeHtml(leak.description())).append("</span><br>\n");
            sb.append("  <span style=\"color:#8b949e;font-size:0.8rem;\">估算洩漏: ")
             .append(formatBytes(leak.estimatedLeakBytes()))
             .append(" | 持續時間: ").append(leak.ageMs() / 1000).append("s</span>\n");
            sb.append("</div>\n");
        }
        return sb.toString();
    }

    private String renderGCTimeline() {
        // Simplified: just show GC event count
        if (snapshots.isEmpty()) return "<p>尚無 GC 數據。</p>";

        var latest = snapshots.get(snapshots.size() - 1);
        return "<p>本次工作階段執行了 <strong>" + latest.gcCount() + "</strong> 次 GC。</p>"
             + "<p style=\"color:#8b949e;font-size:0.8rem;\">"
             + (latest.gcCount() > 10 ? "⚠️ GC 次數較多，考慮增加堆大小或啟用物件池。" : "✅ GC 頻率正常。")
             + "</p>";
    }

    // ─── Utilities ──────────────────────────────────────

    private String formatBytes(long bytes) {
        if (bytes < 1024) return bytes + " B";
        if (bytes < 1024 * 1024) return String.format("%.1f KB", bytes / 1024.0);
        return String.format("%.1f MB", bytes / (1024.0 * 1024));
    }

    private String escapeHtml(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace("\"", "&quot;");
    }

    private String escapeJson(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\").replace("\"", "\\\"")
                .replace("\n", "\\n").replace("\t", "\\t");
    }
}
