package com.francium.forge.config;

import java.io.*;
import java.nio.file.*;
import java.util.*;

/**
 * Forge 設定檔實例
 * 
 * 對應 Forge 的 ModConfig
 * 代表一個實際的設定檔，包含規格和目前的值
 * 
 * @author Francium Team
 * @since 2.5.0
 */
public class ModConfig {
    
    /** 設定類型 */
    private final ModConfigType type;
    
    /** 模組 ID */
    private final String modId;
    
    /** 設定規格 */
    private final ModConfigSpec spec;
    
    /** 設定檔路徑 */
    private Path path;
    
    /** 是否已載入 */
    private boolean loaded = false;
    
    /**
     * 建立設定檔
     * 
     * @param type 設定類型
     * @param modId 模組 ID
     * @param spec 設定規格
     */
    public ModConfig(ModConfigType type, String modId, ModConfigSpec spec) {
        this.type = type;
        this.modId = modId;
        this.spec = spec;
        spec.setModId(modId);
    }
    
    /**
     * 取得設定類型
     */
    public ModConfigType getType() {
        return type;
    }
    
    /**
     * 取得模組 ID
     */
    public String getModId() {
        return modId;
    }
    
    /**
     * 取得設定規格
     */
    public ModConfigSpec getSpec() {
        return spec;
    }
    
    /**
     * 取得設定檔路徑
     */
    public Path getPath() {
        return path;
    }
    
    /**
     * 設定設定檔路徑
     */
    public void setPath(Path path) {
        this.path = path;
    }
    
    /**
     * 檢查是否已載入
     */
    public boolean isLoaded() {
        return loaded;
    }
    
    /**
     * 載入設定檔
     */
    public void load() throws IOException {
        if (path == null) {
            throw new IllegalStateException("Config path not set");
        }
        
        if (!Files.exists(path)) {
            // 檔案不存在，使用預設值
            save();
            loaded = true;
            return;
        }
        
        // 簡單實現：讀取 TOML 格式
        // 實際上應該使用 TOML 解析庫
        Properties props = new Properties();
        try (InputStream is = Files.newInputStream(path)) {
            props.load(is);
        }
        
        // 將屬性應用到設定值
        for (String key : props.stringPropertyNames()) {
            ConfigValue<?> configValue = spec.getValue(key);
            if (configValue != null) {
                setValueFromString(configValue, props.getProperty(key));
            }
        }
        
        loaded = true;
    }
    
    /**
     * 儲存設定檔
     */
    public void save() throws IOException {
        if (path == null) {
            throw new IllegalStateException("Config path not set");
        }
        
        // 確保目錄存在
        Files.createDirectories(path.getParent());
        
        // 簡單實現：寫入 TOML 格式
        // 實際上應該使用 TOML 產生庫
        try (BufferedWriter writer = Files.newBufferedWriter(path)) {
            writer.write("# " + modId + " " + type.name().toLowerCase() + " config");
            writer.newLine();
            writer.write("# Generated by Francium Forge Adapter");
            writer.newLine();
            writer.newLine();
            
            String lastCategory = "";
            for (Map.Entry<String, ConfigValue<?>> entry : spec.getValues().entrySet()) {
                String key = entry.getKey();
                ConfigValue<?> value = entry.getValue();
                
                // 檢查是否需要換類別
                String category = getCategory(key);
                if (!category.equals(lastCategory)) {
                    if (!lastCategory.isEmpty()) {
                        writer.newLine();
                    }
                    writer.write("[" + category + "]");
                    writer.newLine();
                    lastCategory = category;
                }
                
                // 寫入註解
                if (value.getComment() != null && !value.getComment().isEmpty()) {
                    writer.write("# " + value.getComment());
                    writer.newLine();
                }
                
                // 寫入設定值
                writer.write(getShortKey(key) + " = " + valueToString(value.get()));
                writer.newLine();
            }
        }
        
        loaded = true;
    }
    
    /**
     * 重設為預設值
     */
    public void reset() {
        for (ConfigValue<?> value : spec.getValues().values()) {
            value.reset();
        }
    }
    
    /**
     * 取得類別名稱
     */
    private String getCategory(String fullPath) {
        int lastDot = fullPath.lastIndexOf('.');
        if (lastDot > 0) {
            return fullPath.substring(0, lastDot);
        }
        return "general";
    }
    
    /**
     * 取得簡短鍵名
     */
    private String getShortKey(String fullPath) {
        int lastDot = fullPath.lastIndexOf('.');
        if (lastDot >= 0) {
            return fullPath.substring(lastDot + 1);
        }
        return fullPath;
    }
    
    /**
     * 將值轉換為字串
     */
    private String valueToString(Object value) {
        if (value == null) {
            return "";
        }
        if (value instanceof String) {
            return "\"" + value + "\"";
        }
        if (value instanceof Boolean) {
            return value.toString();
        }
        if (value instanceof Number) {
            return value.toString();
        }
        if (value instanceof List) {
            StringBuilder sb = new StringBuilder("[");
            List<?> list = (List<?>) value;
            for (int i = 0; i < list.size(); i++) {
                if (i > 0) sb.append(", ");
                sb.append("\"").append(list.get(i)).append("\"");
            }
            sb.append("]");
            return sb.toString();
        }
        return value.toString();
    }
    
    /**
     * 從字串設定值
     */
    @SuppressWarnings("unchecked")
    private void setValueFromString(ConfigValue<?> configValue, String str) {
        Object defaultValue = configValue.getDefault();
        
        if (defaultValue instanceof Boolean) {
            ((ConfigValue<Boolean>) configValue).set(Boolean.parseBoolean(str));
        } else if (defaultValue instanceof Integer) {
            ((ConfigValue<Integer>) configValue).set(Integer.parseInt(str.trim()));
        } else if (defaultValue instanceof Double) {
            ((ConfigValue<Double>) configValue).set(Double.parseDouble(str.trim()));
        } else if (defaultValue instanceof String) {
            // 移除引號
            String value = str.trim();
            if (value.startsWith("\"") && value.endsWith("\"")) {
                value = value.substring(1, value.length() - 1);
            }
            ((ConfigValue<String>) configValue).set(value);
        }
        // 其他類型暫不支援
    }
}
